name: leagueoflegends
version: '1.0'
summary: leagueoflegends is MOBA game developed and published by Riot Games.
description: |
  League of Legends is a 3D, third-person multiplayer online battle arena (MOBA) game. The game consists of 3 current running game modes: Summoner's Rift, Twisted Treeline, and Howling Abyss.[14] Another game mode, The Crystal Scar, has since been removed. Players compete in matches, lasting anywhere from 20 to 60 minutes on average. In each game mode teams work together to achieve a victory condition, typically destroying the core building (called the Nexus) in the enemy team's base after bypassing a line of defensive structures called turrets, or towers.

  In League of Legends, players assume the role of an unseen "summoner" that controls a "champion" with unique abilities and battle against a team of other players or computer-controlled champions. The goal is usually to destroy the opposing team's "nexus", a structure which lies at the heart of a base protected by defensive structures, although other distinct game modes exist as well. Each League of Legends match is discrete, with all champions starting off fairly weak but increasing in strength by accumulating items and experience over the course of the game. The champions and setting blend a variety of elements, including high fantasy, steampunk, and Lovecraftian horror.

  League of Legends was generally well received upon its release in 2009, and has since grown in popularity, with an active and expansive fanbase. By July 2012, League of Legends was the most played PC game in North America and Europe in terms of the number of hours played. As of January 2014, over 67 million people played League of Legends per month, 27 million per day, and over 7.5 million concurrently during peak hours. League has among the largest footprints of any game in streaming media communities on platforms such as YouTube and Twitch.tv; it routinely ranks first in the most-watched hours. In September 2016 the company estimated that there are over 100 million active players each month. The game's popularity has led it to expand into merchandise, with toys, accessories, apparel, as well as tie-ins to other media through music videos, web series, documentaries, and books.

grade: stable
confinement: devmode
architectures:
  - build-on: amd64
    run-on: amd64
base: core20
compression: lzo

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-staging:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-staging
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

environment:
    WINEPREFIX: "$SNAP_USER_COMMON/.wine"
    INSTALL_URL_NA: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.na.exe"
    INSTALL_URL_EUW: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.euw.exe"
    INSTALL_URL_EUNE: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.eune.exe"
    INSTALL_URL_BR: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.br.exe"
    INSTALL_URL_JP: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.jp.exe"
    INSTALL_URL_KR: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.kr.exe"
    INSTALL_URL_LAN: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.la1.exe"
    INSTALL_URL_LAS: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.la2.exe"
    INSTALL_URL_OCE: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.oc1.exe"
    INSTALL_URL_RU: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.ru.exe"
    INSTALL_URL_TR: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.tr.exe"
    INSTALL_URL_PBE: "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/pbe.pbe.exe"
    TRICKS: "d3dx9"
    LC_ALL: "C.UTF-8"
    NO_AT_BRIDGE: "1"
    SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc

layout:
  /usr/share/libdrm:
    bind: $SNAP/wine-runtime/usr/share/libdrm
  /usr/share/alsa:
    symlink: $SNAP/wine-runtime/usr/share/alsa
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    symlink: $SNAP/wine-runtime/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

apps:
  leagueoflegends:
    command: bin/wrapper
    plugs:
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - process-control
      - audio-playback
      - wayland
      - x11
      - gtk-3-themes
      - icon-themes
      - wine-runtime
      - wine-5-staging
  leagueoflegendsnv:
    command: bin/wrapper
    environment:
      __NV_PRIME_RENDER_OFFLOAD: "1"
      __GLX_VENDOR_LIBRARY_NAME: "nvidia"
      __VK_LAYER_NV_optimus: "NVIDIA_only"
      VK_ICD_FILENAMES: "/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json"
    plugs:
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - process-control
      - audio-playback
      - wayland
      - x11
      - gtk-3-themes
      - icon-themes
      - wine-runtime
      - wine-5-staging
  wineboot:
    command: bin/sommelier $SNAP/wine-platform/wine-staging/bin/wineboot
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - wayland
      - x11
  winecfg:
    command: bin/sommelier $SNAP/wine-platform/wine-staging/bin/winecfg
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - wayland
      - x11
  wineserver:
    command: bin/sommelier $SNAP/wine-platform/wine-staging/bin/wineserver
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - wayland
      - x11
  winetricks:
    command: bin/sommelier $SNAP/wine-runtime/bin/winetricks
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - wayland
      - x11
  regedit:
    command: bin/sommelier $SNAP/wine-platform/wine-staging/bin/regedit
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - wayland
      - x11
  blitzgg:
    command: bin/wrapperb
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - wayland
      - x11
  glxinfo:
    command: bin/sommelier $SNAP/wine-runtime/usr/bin/glxinfo
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - wayland
      - x11
  glxheads:
    command: bin/sommelier $SNAP/wine-runtime/usr/bin/glxheads
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - wayland
      - x11
  vulkaninfo:
    command: bin/sommelier $SNAP/wine-runtime/usr/bin/vulkaninfo
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - wayland
      - x11
  vkcube:
    command: bin/sommelier $SNAP/wine-runtime/usr/bin/vkcube
    environment:
      VK_INSTANCE_LAYERS: "VK_LAYER_MESA_overlay"
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - wayland
      - x11
  vkcube-nv:
    command: bin/sommelier $SNAP/wine-runtime/usr/bin/vkcube
    environment:
      __NV_PRIME_RENDER_OFFLOAD: "1"
      __GLX_VENDOR_LIBRARY_NAME: "nvidia"
      __VK_LAYER_NV_optimus: "NVIDIA_only"
      VK_ICD_FILENAMES: "/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json"
      VK_INSTANCE_LAYERS: "VK_LAYER_MESA_overlay"
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - wayland
      - x11

parts:
  leagueoflegends:
    plugin: dump
    source: ./snap/local/scripts
    override-build: |
      snapcraftctl build
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-runtime
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-platform
    organize:
      'lolfix': bin/
      'sommelier': bin/
      'wrapper': bin/
      'wrapperb': bin/
